In [ ]:
import numpy as np

In [ ]:
array = np.array([1, 2, 3])
print(array)

In [ ]:
array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print(array2.shape)

In [ ]:
array3 = array2.reshape(3,5)
print(array3)

In [24]:
print("shape ", array3.shape)

shape  (3, 5)


In [25]:
print("dimension ",array3.ndim)

dimension  2


In [26]:
print("data type ",array3.dtype.name)

data type  int64


In [ ]:
print("size ",array3.size)

In [29]:
print("type ", type(array3))

type  <class 'numpy.ndarray'>


In [32]:
array4 = np.array([[1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(array4)
print("dimension ",array4.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
dimension  2


In [35]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
zeros[0,0] = 5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
np.empty((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [43]:
a = np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [47]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[  1  32 729]


In [51]:
a = np.array([1,2,3])
b = a
c = b
c[0] = 5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [49]:
a = np.array([1,2,3])
d = a.copy()
a[0] = 50
print(a,d)

[50  2  3] [1 2 3]


In [50]:
a = np.array([1,2,13,4,5,6,7,8])
a[4:8]

array([5, 6, 7, 8])

In [53]:
a[::-1]

array([3, 2, 5])

In [55]:
b = np.array([[1,2,3,4], [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
print(b[1,1])

6


In [58]:
print(b[: ,1])

[2 6]


In [59]:
print(b[1, :])

[5 6 7 8]


In [64]:
b[1,1:4]

array([6, 7, 8])

In [65]:
b[:, -1]

array([4, 8])

In [66]:
b = b.ravel()
b

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
b.T

array([1, 2, 3, 4, 5, 6, 7, 8])